### PR TITLE
Cleanup.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️

- Add type hints properties.
- Add methods setCssFiles(), setJsFiles().

### CODE REVIEW

**Comment by terabytesoftw** [comment]
What do you think about eliminating the type hints of setters, since they are defined in the properties.

**Comment by samdark** [comment]
@terabytesoftw not a good idea, I think.

**Comment by rob006** [comment]
> What do you think about eliminating the type hints of setters, since they are defined in the properties.

I would rather eliminate type from private properties if their type is ensured by constructor and setters.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
