### PR TITLE
Add WebView::renderString()

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by terabytesoftw** [comment]
What is the use case?

**Comment by vjik** [comment]
> What is the use case?

For example, return widget as result of ajax request.

```php
$webView->renderString(ModalWidget::widget()->render)
```

**Comment by samdark** [comment]
That does not solve the issue. The issue was about taking templates from database, not about echoing strings with triggering events.

**Comment by vjik** [comment]
> That does not solve the issue. The issue was about taking templates from database, not about echoing strings with triggering events.

oh, yes.

But, `renderString` is useful also. See example in my previous comment.

**Comment by samdark** [comment]
Well, that's more like `renderAjaxString`.

**Comment by vjik** [comment]
> Well, that's more like `renderAjaxString`.

Done

**Comment by samdark** [comment]
renderAjax could now use renderAjaxString.

**Comment by vjik** [comment]
> renderAjax could now use renderAjaxString.

No, events PageBegin, BodyBegin should be fire before render file. If first render file, then fire events, this can lead to errors in some cases.

**Comment by samdark** [comment]
See issue about the reason for closing it.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
