### PR TITLE
Set logger optional + fix tests for windows

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Use `NullLogger::class un `LoggerInterface::class` it's very simple.

**Comment by vjik** [comment]
My idea: next make eventdispatcher optional and remove 

```
"psr/container-implementation": "1.0.0",
"psr/event-dispatcher": "1.0.0",
"psr/event-dispatcher-implementation": "1.0.0",
"psr/log": "^1.1",
```

... this is to much for renderring views.

**Comment by terabytesoftw** [comment]
Dependencies exist the same in the constructor so they must go in require not require-dev.

**Comment by vjik** [comment]
> Dependencies exist the same in the constructor so they must go in require not require-dev.

Yes, so I want make him optional `?EventDispatcherInterface`

**Comment by samdark** [comment]
I don't like the idea. Some PSR dependencies aren't too much. These are pretty normal.

**Pull request closed without merging**
