### PR TITLE
Replaced '/' by DIRECTORY SEPARATOR

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
Is there a reason for it?

**Comment by xepozz** [comment]
Yes, cross-platform :) 
Windows users will say thanks for this PR

**Comment by samdark** [comment]
I am a Windows user and I don't see why it should be changed. `/` works fine in Windows unless you're working with a path obtained from files API i.e. asset path would work well with `/`, it will be fine when passed to `is_file()` and other file-related methods.

**Comment by xepozz** [comment]
Hm... I unterstand you, but that constant was born only for this.
Ok. I think this moment must be fixed in the documentation for contributors.

**Pull request closed without merging**
